# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details


version: 2

formats:
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    - >
      docker run --rm
      -v "$(pwd):/data:ro"
      -v "$READTHEDOCS_OUTPUT/html/:/phpdoc_out"
      "phpdoc/phpdoc:3"
      --cache-folder "/tmp/phpdoc.cache"
      --target "/phpdoc_out"
