# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - php-cli
    - php-mbstring
    - php-xml
    - graphviz
    - plantuml
  jobs:
    pre_build:
      - wget https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.9.1/phpDocumentor.phar -O /tmp/phpDocumentor.phar
      - php /tmp/phpDocumentor.phar

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip

python:
  install:
    - requirements: docs/requirements.txt

